export const INDUSTRIES_DATA = [
  {
    id: 'whitegood',
    title: 'White Goods',
    subtitle: 'Household Appliances',
    description: 'Energy-efficient motor solutions for refrigerators, washing machines, dishwashers, and air conditioning units. Our sensorless control technology reduces energy consumption while maintaining quiet operation and reliability.',
    features: ['Refrigerator compressors', 'Washing machine drums', 'Dishwasher pumps', 'AC fan motors'],
    stat: '40%',
    statLabel: 'energy savings',
    color: '#2b6bc4',
    image: 'https://images.pexels.com/photos/5591581/pexels-photo-5591581.jpeg?auto=compress&cs=tinysrgb&w=800',
    imageAlt: 'Modern household washing machine representing white goods industry',
  },
  {
    id: 'powertool',
    title: 'Power Tools',
    subtitle: 'Professional & Consumer',
    description: 'High-performance, brushless motor control for cordless drills, angle grinders, and professional power tools. Optimized for torque response, efficiency, and long battery life in demanding applications.',
    features: ['Cordless drills', 'Angle grinders', 'Circular saws', 'Impact drivers'],
    stat: '2x',
    statLabel: 'battery life',
    color: '#c42b2b',
    image: 'https://images.pexels.com/photos/1249611/pexels-photo-1249611.jpeg?auto=compress&cs=tinysrgb&w=800',
    imageAlt: 'Professional power tools and cordless drills',
  },
  {
    id: 'automotive',
    title: 'Automotive',
    subtitle: 'Vehicle Systems',
    description: 'Automotive-grade motor control for pumps, fans, wipers, and comfort systems. Our solutions meet stringent quality and safety requirements, with AUTOSAR-compatible software for seamless vehicle integration.',
    features: ['Fuel & water pumps', 'Radiator fans', 'Wiper systems', 'Seat adjustment'],
    stat: '1M+',
    statLabel: 'units deployed',
    color: '#1a8a50',
    image: 'https://images.pexels.com/photos/3862634/pexels-photo-3862634.jpeg?auto=compress&cs=tinysrgb&w=800',
    imageAlt: 'Automotive production line with electronic vehicle systems',
  },
];
