export const INDUSTRIES_DATA = [
  {
    id: 'whitegood',
    title: 'White Goods',
    subtitle: 'Household Appliances',
    description: 'Energy-efficient motor solutions for refrigerators, washing machines, dishwashers, and air conditioning units. Our sensorless control technology reduces energy consumption while maintaining quiet operation and reliability.',
    features: ['Refrigerator compressors', 'Washing machine drums', 'Dishwasher pumps', 'AC fan motors'],
    stat: '40%',
    statLabel: 'energy savings',
    color: '#2b6bc4',
    image: '/images/whitegoods-washing-machine.png',
    imageAlt: 'Modern household washing machine representing white goods industry',
  },
  {
    id: 'powertool',
    title: 'Power Tools',
    subtitle: 'Professional & Consumer',
    description: 'High-performance, brushless motor control for cordless drills, angle grinders, and professional power tools. Optimized for torque response, efficiency, and long battery life in demanding applications.',
    features: ['Cordless drills', 'Angle grinders', 'Circular saws', 'Impact drivers'],
    stat: '2x',
    statLabel: 'battery life',
    color: '#c42b2b',
    image: '/images/power-tools-drill.png',
    imageAlt: 'Professional power tools and cordless drills',
  },
  {
    id: 'automotive',
    title: 'Automotive',
    subtitle: 'Vehicle Systems',
    description: 'Automotive-grade motor control for pumps, fans, wipers, and comfort systems. Our solutions meet stringent quality and safety requirements, with AUTOSAR-compatible software for seamless vehicle integration.',
    features: ['Fuel & water pumps', 'Radiator fans', 'Wiper systems', 'Seat adjustment'],
    stat: '1M+',
    statLabel: 'units deployed',
    color: '#1a8a50',
    image: '/images/automotive-suv.png',
    imageAlt: 'Modern SUV representing automotive and vehicle systems',
  },
  {
    id: 'ebike',
    title: 'E-bike',
    subtitle: 'Electric Bicycles',
    description: 'Sensorless motor control for pedal-assist and throttle e-bikes. Our solutions deliver smooth torque response, high efficiency, and long battery life for mid-drive and hub motors, meeting the demands of premium electric bicycles.',
    features: ['Mid-drive & hub motors', 'Pedal assist & torque sensing', 'Regenerative braking', 'Battery efficiency'],
    stat: 'EV-ready',
    statLabel: 'solutions',
    color: '#0ea5e9',
    image: '/images/industries-ebike.png',
    imageAlt: 'Modern e-bike representing electric bicycle solutions',
  },
];
